### ISSUE TITLE
Prevent initial Modal focus on close button

### ISSUE THREAD

**Issue by smathson** [FieldLevel/FieldLevelPlaybook#97]
Currently we immediately focus the first interactive element when a Modal is opened but this is always the close button which looks weird and is also not the action we want a user to take immediately. Either add `tabindex=-1` to the close button so that it's not a focusable element or move it lower in the DOM so that it's the last item to be focused when tabbing through elements.

**Comment by JeremyWeir** [comment]
I feel like there is css to disable accessibility outlines
